// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db

import (
	"context"

	"github.com/bamItsCam/nft-tickets/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// BurnTicket provides a mock function for the type MockQuerier
func (_mock *MockQuerier) BurnTicket(ctx context.Context, id int32) (db.Ticket, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BurnTicket")
	}

	var r0 db.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (db.Ticket, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) db.Ticket); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Ticket)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_BurnTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BurnTicket'
type MockQuerier_BurnTicket_Call struct {
	*mock.Call
}

// BurnTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerier_Expecter) BurnTicket(ctx interface{}, id interface{}) *MockQuerier_BurnTicket_Call {
	return &MockQuerier_BurnTicket_Call{Call: _e.mock.On("BurnTicket", ctx, id)}
}

func (_c *MockQuerier_BurnTicket_Call) Run(run func(ctx context.Context, id int32)) *MockQuerier_BurnTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_BurnTicket_Call) Return(ticket db.Ticket, err error) *MockQuerier_BurnTicket_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockQuerier_BurnTicket_Call) RunAndReturn(run func(ctx context.Context, id int32) (db.Ticket, error)) *MockQuerier_BurnTicket_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvent provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateEvent(ctx context.Context, arg db.CreateEventParams) (db.Event, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 db.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateEventParams) (db.Event, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateEventParams) db.Event); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Event)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateEventParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockQuerier_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateEventParams
func (_e *MockQuerier_Expecter) CreateEvent(ctx interface{}, arg interface{}) *MockQuerier_CreateEvent_Call {
	return &MockQuerier_CreateEvent_Call{Call: _e.mock.On("CreateEvent", ctx, arg)}
}

func (_c *MockQuerier_CreateEvent_Call) Run(run func(ctx context.Context, arg db.CreateEventParams)) *MockQuerier_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateEventParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateEventParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateEvent_Call) Return(event db.Event, err error) *MockQuerier_CreateEvent_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockQuerier_CreateEvent_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateEventParams) (db.Event, error)) *MockQuerier_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTicket provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateTicket(ctx context.Context, arg db.CreateTicketParams) (db.Ticket, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateTicket")
	}

	var r0 db.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateTicketParams) (db.Ticket, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateTicketParams) db.Ticket); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Ticket)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateTicketParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTicket'
type MockQuerier_CreateTicket_Call struct {
	*mock.Call
}

// CreateTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateTicketParams
func (_e *MockQuerier_Expecter) CreateTicket(ctx interface{}, arg interface{}) *MockQuerier_CreateTicket_Call {
	return &MockQuerier_CreateTicket_Call{Call: _e.mock.On("CreateTicket", ctx, arg)}
}

func (_c *MockQuerier_CreateTicket_Call) Run(run func(ctx context.Context, arg db.CreateTicketParams)) *MockQuerier_CreateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateTicketParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateTicketParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateTicket_Call) Return(ticket db.Ticket, err error) *MockQuerier_CreateTicket_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockQuerier_CreateTicket_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateTicketParams) (db.Ticket, error)) *MockQuerier_CreateTicket_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (db.User, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) db.User); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQuerier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateUserParams
func (_e *MockQuerier_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockQuerier_CreateUser_Call {
	return &MockQuerier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockQuerier_CreateUser_Call) Run(run func(ctx context.Context, arg db.CreateUserParams)) *MockQuerier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateUser_Call) Return(user db.User, err error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockQuerier_CreateUser_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateUserParams) (db.User, error)) *MockQuerier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTicket provides a mock function for the type MockQuerier
func (_mock *MockQuerier) DeleteTicket(ctx context.Context, id int32) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTicket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_DeleteTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTicket'
type MockQuerier_DeleteTicket_Call struct {
	*mock.Call
}

// DeleteTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerier_Expecter) DeleteTicket(ctx interface{}, id interface{}) *MockQuerier_DeleteTicket_Call {
	return &MockQuerier_DeleteTicket_Call{Call: _e.mock.On("DeleteTicket", ctx, id)}
}

func (_c *MockQuerier_DeleteTicket_Call) Run(run func(ctx context.Context, id int32)) *MockQuerier_DeleteTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_DeleteTicket_Call) Return(err error) *MockQuerier_DeleteTicket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_DeleteTicket_Call) RunAndReturn(run func(ctx context.Context, id int32) error) *MockQuerier_DeleteTicket_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvent provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetEvent(ctx context.Context, id int32) (db.Event, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 db.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (db.Event, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) db.Event); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Event)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvent'
type MockQuerier_GetEvent_Call struct {
	*mock.Call
}

// GetEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerier_Expecter) GetEvent(ctx interface{}, id interface{}) *MockQuerier_GetEvent_Call {
	return &MockQuerier_GetEvent_Call{Call: _e.mock.On("GetEvent", ctx, id)}
}

func (_c *MockQuerier_GetEvent_Call) Run(run func(ctx context.Context, id int32)) *MockQuerier_GetEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetEvent_Call) Return(event db.Event, err error) *MockQuerier_GetEvent_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockQuerier_GetEvent_Call) RunAndReturn(run func(ctx context.Context, id int32) (db.Event, error)) *MockQuerier_GetEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetTicket provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetTicket(ctx context.Context, id int32) (db.Ticket, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTicket")
	}

	var r0 db.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (db.Ticket, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) db.Ticket); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Ticket)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTicket'
type MockQuerier_GetTicket_Call struct {
	*mock.Call
}

// GetTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerier_Expecter) GetTicket(ctx interface{}, id interface{}) *MockQuerier_GetTicket_Call {
	return &MockQuerier_GetTicket_Call{Call: _e.mock.On("GetTicket", ctx, id)}
}

func (_c *MockQuerier_GetTicket_Call) Run(run func(ctx context.Context, id int32)) *MockQuerier_GetTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetTicket_Call) Return(ticket db.Ticket, err error) *MockQuerier_GetTicket_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockQuerier_GetTicket_Call) RunAndReturn(run func(ctx context.Context, id int32) (db.Ticket, error)) *MockQuerier_GetTicket_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUser(ctx context.Context, id int32) (db.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (db.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) db.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockQuerier_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerier_Expecter) GetUser(ctx interface{}, id interface{}) *MockQuerier_GetUser_Call {
	return &MockQuerier_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockQuerier_GetUser_Call) Run(run func(ctx context.Context, id int32)) *MockQuerier_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUser_Call) Return(user db.User, err error) *MockQuerier_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockQuerier_GetUser_Call) RunAndReturn(run func(ctx context.Context, id int32) (db.User, error)) *MockQuerier_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByWallet provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserByWallet(ctx context.Context, walletAddress string) (db.User, error) {
	ret := _mock.Called(ctx, walletAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByWallet")
	}

	var r0 db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return returnFunc(ctx, walletAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = returnFunc(ctx, walletAddress)
	} else {
		r0 = ret.Get(0).(db.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, walletAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserByWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByWallet'
type MockQuerier_GetUserByWallet_Call struct {
	*mock.Call
}

// GetUserByWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - walletAddress string
func (_e *MockQuerier_Expecter) GetUserByWallet(ctx interface{}, walletAddress interface{}) *MockQuerier_GetUserByWallet_Call {
	return &MockQuerier_GetUserByWallet_Call{Call: _e.mock.On("GetUserByWallet", ctx, walletAddress)}
}

func (_c *MockQuerier_GetUserByWallet_Call) Run(run func(ctx context.Context, walletAddress string)) *MockQuerier_GetUserByWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserByWallet_Call) Return(user db.User, err error) *MockQuerier_GetUserByWallet_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockQuerier_GetUserByWallet_Call) RunAndReturn(run func(ctx context.Context, walletAddress string) (db.User, error)) *MockQuerier_GetUserByWallet_Call {
	_c.Call.Return(run)
	return _c
}

// ListEvents provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListEvents(ctx context.Context) ([]db.Event, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 []db.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]db.Event, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []db.Event); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEvents'
type MockQuerier_ListEvents_Call struct {
	*mock.Call
}

// ListEvents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) ListEvents(ctx interface{}) *MockQuerier_ListEvents_Call {
	return &MockQuerier_ListEvents_Call{Call: _e.mock.On("ListEvents", ctx)}
}

func (_c *MockQuerier_ListEvents_Call) Run(run func(ctx context.Context)) *MockQuerier_ListEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuerier_ListEvents_Call) Return(events []db.Event, err error) *MockQuerier_ListEvents_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockQuerier_ListEvents_Call) RunAndReturn(run func(ctx context.Context) ([]db.Event, error)) *MockQuerier_ListEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListTicketsByEvent provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListTicketsByEvent(ctx context.Context, eventID int32) ([]db.Ticket, error) {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ListTicketsByEvent")
	}

	var r0 []db.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]db.Ticket, error)); ok {
		return returnFunc(ctx, eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []db.Ticket); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListTicketsByEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTicketsByEvent'
type MockQuerier_ListTicketsByEvent_Call struct {
	*mock.Call
}

// ListTicketsByEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int32
func (_e *MockQuerier_Expecter) ListTicketsByEvent(ctx interface{}, eventID interface{}) *MockQuerier_ListTicketsByEvent_Call {
	return &MockQuerier_ListTicketsByEvent_Call{Call: _e.mock.On("ListTicketsByEvent", ctx, eventID)}
}

func (_c *MockQuerier_ListTicketsByEvent_Call) Run(run func(ctx context.Context, eventID int32)) *MockQuerier_ListTicketsByEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListTicketsByEvent_Call) Return(tickets []db.Ticket, err error) *MockQuerier_ListTicketsByEvent_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockQuerier_ListTicketsByEvent_Call) RunAndReturn(run func(ctx context.Context, eventID int32) ([]db.Ticket, error)) *MockQuerier_ListTicketsByEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ListTicketsByOwner provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListTicketsByOwner(ctx context.Context, ownerID int32) ([]db.Ticket, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListTicketsByOwner")
	}

	var r0 []db.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]db.Ticket, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []db.Ticket); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListTicketsByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTicketsByOwner'
type MockQuerier_ListTicketsByOwner_Call struct {
	*mock.Call
}

// ListTicketsByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int32
func (_e *MockQuerier_Expecter) ListTicketsByOwner(ctx interface{}, ownerID interface{}) *MockQuerier_ListTicketsByOwner_Call {
	return &MockQuerier_ListTicketsByOwner_Call{Call: _e.mock.On("ListTicketsByOwner", ctx, ownerID)}
}

func (_c *MockQuerier_ListTicketsByOwner_Call) Run(run func(ctx context.Context, ownerID int32)) *MockQuerier_ListTicketsByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListTicketsByOwner_Call) Return(tickets []db.Ticket, err error) *MockQuerier_ListTicketsByOwner_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockQuerier_ListTicketsByOwner_Call) RunAndReturn(run func(ctx context.Context, ownerID int32) ([]db.Ticket, error)) *MockQuerier_ListTicketsByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTicketOwner provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateTicketOwner(ctx context.Context, arg db.UpdateTicketOwnerParams) (db.Ticket, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTicketOwner")
	}

	var r0 db.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateTicketOwnerParams) (db.Ticket, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateTicketOwnerParams) db.Ticket); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Ticket)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.UpdateTicketOwnerParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpdateTicketOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTicketOwner'
type MockQuerier_UpdateTicketOwner_Call struct {
	*mock.Call
}

// UpdateTicketOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTicketOwnerParams
func (_e *MockQuerier_Expecter) UpdateTicketOwner(ctx interface{}, arg interface{}) *MockQuerier_UpdateTicketOwner_Call {
	return &MockQuerier_UpdateTicketOwner_Call{Call: _e.mock.On("UpdateTicketOwner", ctx, arg)}
}

func (_c *MockQuerier_UpdateTicketOwner_Call) Run(run func(ctx context.Context, arg db.UpdateTicketOwnerParams)) *MockQuerier_UpdateTicketOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.UpdateTicketOwnerParams
		if args[1] != nil {
			arg1 = args[1].(db.UpdateTicketOwnerParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateTicketOwner_Call) Return(ticket db.Ticket, err error) *MockQuerier_UpdateTicketOwner_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockQuerier_UpdateTicketOwner_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateTicketOwnerParams) (db.Ticket, error)) *MockQuerier_UpdateTicketOwner_Call {
	_c.Call.Return(run)
	return _c
}
