// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events(name, date, venue, capacity)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, name, date, venue, capacity
`

type CreateEventParams struct {
	Name     string
	Date     time.Time
	Venue    string
	Capacity int32
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.Date,
		arg.Venue,
		arg.Capacity,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Date,
		&i.Venue,
		&i.Capacity,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, created_at, name, date, venue, capacity FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int32) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Date,
		&i.Venue,
		&i.Capacity,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, created_at, name, date, venue, capacity FROM events
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.Date,
			&i.Venue,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
