// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Event struct {
	ID        int32
	CreatedAt time.Time
	Name      string
	Date      time.Time
	Venue     string
	Capacity  int32
}

type Ticket struct {
	ID        int32
	CreatedAt time.Time
	EventID   int32
	OwnerID   int32
	BurnedAt  *time.Time
}

type User struct {
	ID            int32
	CreatedAt     time.Time
	Email         string
	WalletAddress string
}
