// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	BurnTicket(ctx context.Context, id int32) (Ticket, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTicket(ctx context.Context, id int32) error
	GetEvent(ctx context.Context, id int32) (Event, error)
	GetTicket(ctx context.Context, id int32) (Ticket, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByWallet(ctx context.Context, walletAddress string) (User, error)
	ListEvents(ctx context.Context) ([]Event, error)
	ListTicketsByEvent(ctx context.Context, eventID int32) ([]Ticket, error)
	ListTicketsByOwner(ctx context.Context, ownerID int32) ([]Ticket, error)
	UpdateTicketOwner(ctx context.Context, arg UpdateTicketOwnerParams) (Ticket, error)
}

var _ Querier = (*Queries)(nil)
