// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"
)

const burnTicket = `-- name: BurnTicket :one
UPDATE tickets SET burned_at = NOW()
WHERE id = $1
RETURNING id, created_at, event_id, owner_id, burned_at
`

func (q *Queries) BurnTicket(ctx context.Context, id int32) (Ticket, error) {
	row := q.db.QueryRow(ctx, burnTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EventID,
		&i.OwnerID,
		&i.BurnedAt,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets(event_id, owner_id)
VALUES ($1, $2)
RETURNING id, created_at, event_id, owner_id, burned_at
`

type CreateTicketParams struct {
	EventID int32
	OwnerID int32
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket, arg.EventID, arg.OwnerID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EventID,
		&i.OwnerID,
		&i.BurnedAt,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets
WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTicket, id)
	return err
}

const getTicket = `-- name: GetTicket :one
SELECT id, created_at, event_id, owner_id, burned_at FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id int32) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EventID,
		&i.OwnerID,
		&i.BurnedAt,
	)
	return i, err
}

const listTicketsByEvent = `-- name: ListTicketsByEvent :many
SELECT id, created_at, event_id, owner_id, burned_at from tickets
WHERE event_id = $1
`

func (q *Queries) ListTicketsByEvent(ctx context.Context, eventID int32) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.EventID,
			&i.OwnerID,
			&i.BurnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByOwner = `-- name: ListTicketsByOwner :many
SELECT id, created_at, event_id, owner_id, burned_at from tickets
WHERE owner_id = $1
`

func (q *Queries) ListTicketsByOwner(ctx context.Context, ownerID int32) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.EventID,
			&i.OwnerID,
			&i.BurnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketOwner = `-- name: UpdateTicketOwner :one
UPDATE tickets set owner_id = $2
WHERE id = $1
RETURNING id, created_at, event_id, owner_id, burned_at
`

type UpdateTicketOwnerParams struct {
	ID      int32
	OwnerID int32
}

func (q *Queries) UpdateTicketOwner(ctx context.Context, arg UpdateTicketOwnerParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketOwner, arg.ID, arg.OwnerID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EventID,
		&i.OwnerID,
		&i.BurnedAt,
	)
	return i, err
}
