// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(email, wallet_address)
VALUES ($1, $2)
RETURNING id, created_at, email, wallet_address
`

type CreateUserParams struct {
	Email         string
	WalletAddress string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.WalletAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.WalletAddress,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, email, wallet_address FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.WalletAddress,
	)
	return i, err
}

const getUserByWallet = `-- name: GetUserByWallet :one
SELECT id, created_at, email, wallet_address FROM users
WHERE wallet_address = $1
`

func (q *Queries) GetUserByWallet(ctx context.Context, walletAddress string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWallet, walletAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.WalletAddress,
	)
	return i, err
}
